CREATE OR REPLACE FUNCTION CALCULAR_VALOR_MOV(QTD NUMBER)
RETURN NUMBER
IS
    VALOR NUMBER;
BEGIN
    IF QTD <= 10 THEN
        VALOR := QTD * 1.00;
    ELSIF QTD <= 20 THEN
        VALOR := QTD * 0.75;
    ELSE
        VALOR := QTD * 0.50;
    END IF;

    RETURN VALOR;
END;
/
